### PR TITLE
Get rid of credentials

### PR DESCRIPTION
**Pull request by JesseAye**

### CODE REVIEW

**Comment by oguzhanKomcu** [comment]
Thank you very much. I did this to try it here, but forgot to delete it. Actually, I was going to show you how to use it in another topic. I'm glad you saw it and let me know. :D

**Comment by JesseAye** [comment]
No problem!
I'm trying to learn more about Git and GitHub, was there another way you could show me how to bring up issues?

**Comment by oguzhanKomcu** [comment]
I'm a student too, maybe you've noticed, but I really liked when someone
looked at my profile and replied. I don't know how to use GitHub for these
reasons. How did you see that mistake? Are you following from the homepage.
Did you catch it from there?

Jesse Ayala ***@***.***>, 17 Şub 2022 Per, 02:15 tarihinde
şunu yazdı:

**Comment by JesseAye** [comment]
I was just browsing through the C# topic on this site, looking for any projects I could contribute to. I was looking through your project when I noticed the issue!

**Comment by oguzhanKomcu** [comment]
Can I consult you when I have difficulties in my projects?

Jesse Ayala ***@***.***>, 17 Şub 2022 Per, 03:37 tarihinde
şunu yazdı:

**Comment by JesseAye** [comment]
Certainly! I don't mind helping out whenever I can :)

**Pull request merged**
